DEFAULT_AUDIO_PROMPT = "alba"
DEFAULT_VARIANT = "b6369a24"
DEFAULT_TEMPERATURE = 0.7
DEFAULT_LSD_DECODE_STEPS = 1
DEFAULT_NOISE_CLAMP = None
DEFAULT_EOS_THRESHOLD = -4.0
DEFAULT_FRAMES_AFTER_EOS = None
MAX_TOKEN_PER_CHUNK = 50

# Streaming optimization configuration
DEFAULT_ENABLE_ADAPTIVE_CHUNKING = True
DEFAULT_ADAPTIVE_CHUNKING_THRESHOLD_WORDS = 20

# Queue monitoring configuration
DEFAULT_QUEUE_MONITORING_ENABLED = True
DEFAULT_QUEUE_WARNING_THRESHOLD = 10
DEFAULT_QUEUE_CRITICAL_THRESHOLD = 20

# Backpressure configuration
DEFAULT_BACKPRESSURE_ENABLED = True
DEFAULT_BACKPRESSURE_THRESHOLD = 15
DEFAULT_BACKPRESSURE_SLEEP_MS = 10
