//! NumPy top-level module exports
//!
//! This module re-exports all NumPy top-level functions to match Python's numpy namespace.
//! Functions are organized by category for maintainability.

pub use crate::array::{arange, empty, eye, full, linspace, logspace, ones, zeros};

pub use crate::array_extra::{
    // Mathematical operations that are top-level in NumPy
    add,
    byteswap,
    // Additional critical functions that were namespace-mismatched
    choose,
    compress,
    concatenate,
    diag,
    diagonal,
    divide,
    dump,
    dumps,
    // Array manipulation
    flatten,
    getfield,
    hstack,
    item,
    maximum,
    minimum,
    multiply,
    put,
    ravel,
    repeat,
    reshape,
    resize,
    round,
    searchsorted,
    setfield,
    setflags,
    sort,
    split,
    squeeze,
    stack,
    subtract,
    take,
    tile,
    tobytes,
    tofile,
    tolist,
    transpose,
    view,
    vstack,
};

pub use crate::comparison_ufuncs::{
    equal,
    greater,
    greater_equal,
    less,
    less_equal,
    // Additional comparison functions
    not_equal,
};

pub use crate::math_ufuncs::{
    // Additional mathematical functions
    absolute,
    arccos,
    arccosh,
    arcsin,
    arcsinh,
    arctan,
    arctan2,
    arctanh,
    around,
    ceil,
    cos,
    degrees,
    exp,
    fabs,
    floor,
    fmod,
    hypot,
    log,
    radians,
    rint,
    sign,
    sin,
    sqrt,
    tan,
    trunc,
};

pub use crate::reductions::{
    all,
    any,
    argmax,
    argmin,
    // Additional reduction functions
    cumprod,
    cumsum,
    max,
    mean,
    min,
    nancumprod,
    nancumsum,
    nansum,
    negative,
    prod,
    std,
    sum,
    var,
};

pub use crate::linalg::{
    cholesky,
    cond,
    det,
    eig,
    eigh,
    eigvals,
    eigvalsh,
    inv,
    lstsq,
    lu,
    matrix_norm,
    // Linear algebra functions
    matrix_power,
    matrix_rank,
    norm,
    pinv,
    qr,
    schur,
    slogdet,
    solve,
    svd,
    tensorinv,
    tensorsolve,
    trace,
};

pub use crate::random::{
    beta,
    binomial,
    chisquare,
    choice,
    exponential,
    f,
    gamma,
    geometric,
    get_state,
    hypergeometric,
    lognormal,
    logseries,
    multinomial,
    negative_binomial,
    noncentral_chisquare,
    noncentral_f,
    noncentral_t,
    normal,
    pareto,
    poisson,
    power,
    random,
    random_sample,
    ranf,
    rayleigh,
    sample,
    // Random functions
    seed,
    set_state,
    standard_cauchy,
    standard_exponential,
    standard_gamma,
    standard_normal,
    standard_t,
    triangular,
    uniform,
    vonmises,
    wald,
    weibull,
    zipf,
};

pub use crate::char::{
    // String/array operations
    add,
    capitalize,
    center,
    count,
    decode,
    encode,
    endswith,
    expandtabs,
    find,
    index,
    isalnum,
    isalpha,
    isdecimal,
    isdigit,
    islower,
    isnumeric,
    isspace,
    istitle,
    isupper,
    join,
    ljust,
    lower,
    lstrip,
    partition,
    replace,
    rfind,
    rindex,
    rjust,
    rpartition,
    rsplit,
    rstrip,
    split,
    splitlines,
    startswith,
    strip,
    swapcase,
    title,
    translate,
    upper,
    zfill,
};

/// Convenience re-exports
pub use crate::array::Array;
